services:
  - type: web
    name: blush-discord
    runtime: node
    repo: https://github.com/zuwlu/blush-discord
    buildCommand: yarn install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
